repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args: ["--autofix", "--indent=2", "--no-sort-keys"]

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: ["--line-length", "100"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.14"
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-ruff
        args: ["--fix"]
      - id: nbqa-isort
        args: ["--profile=black"]
        additional_dependencies: [isort==5.6.4]
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: ["--py37-plus"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        language_version: system
        files: "\\.(\
          css|less|scss\
          |graphql|gql\
          |html\
          |js|jsx\
          |json\
          |ts|tsx\
          |vue\
          |yaml|yml\
          )$"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier-markdown
        language_version: system
        entry: prettier --write --parser mdx
        files: "\\.(\
          |md|markdown|mdown|mkdn\
          |mdx\
          )$"
