name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: main

jobs:
  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          environment-file: binder/environment.yml
          python-version: ${{ matrix.python-version }}
          activate-environment: python3
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - shell: bash -l {0}
        run: |
          mamba install -c conda-forge jupyter nbconvert
          # jupyter kernelspec install --user --name python3
      - shell: bash -l {0}
        name: Running Tests
        run: |
          for nb in **/*.ipynb; do
            echo $nb
            # skip Inline-Statistics until we can install carbonplan-forest-offsets from pypi
            if [[ $nb == "notebooks/Inline-Statistics.ipynb" ]]; then
              echo "skipping $nb"
              continue
            fi
            time jupyter nbconvert --to notebook --execute $nb
          done

  repo2docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files in repo
        uses: actions/checkout@main
      - name: update jupyter dependencies with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: "true"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v2.0.3
